export let REQUEST_GET_AGENT_DAYLY_SCHEDULE_SUCCESS = 'REQUEST_GET_AGENT_DAYLY_SCHEDULE_SUCCESS';
export const REQUEST_GET_WEEK_DAY_LIST_SUCCESS = 'REQUEST_GET_WEEK_DAY_LIST_SUCCESS';
export const REQUEST_GET_AGENT_SCHEDULE_LIST_SUCCESS = 'REQUEST_GET_AGENT_SCHEDULE_LIST_SUCCESS';
export const REQUEST_GET_COUNTRY_LIST_START = 'REQUEST_GET_COUNTRY_LIST_START';
export const REQUEST_GET_COUNTRY_LIST_SUCCESS = 'REQUEST_GET_COUNTRY_LIST_SUCCESS';

export const REQUEST_SERVICE_PRICE_START = 'REQUEST_SERVICE_PRICE_START';
export const REQUEST_SERVICE_PRICE_SUCCESS = 'REQUEST_SERVICE_PRICE_SUCCESS';
export const REQUEST_SERVICE_PRICE_ERROR = 'REQUEST_SERVICE_PRICE_ERROR';
export const REQUEST_GET_SERVICE_PRICE_LIST_SUCCESS = 'REQUEST_GET_SERVICE_PRICE_LIST_SUCCESS';
export const REQUEST_GET_SERVICE_PRICE_DASHBOARD_LIST_SUCCESS = 'REQUEST_GET_SERVICE_PRICE_DASHBOARD_LIST_SUCCESS';
export const REQUEST_GET_SERVICE_PRICE_BY_SERVICE_LIST_SUCCESS = 'REQUEST_GET_SERVICE_PRICE_BY_SERVICE_LIST_SUCCESS';
export const REQUEST_GET_SERVICE_PRICE_BY_STATE_LIST_SUCCESS = 'REQUEST_GET_SERVICE_PRICE_BY_STATE_LIST_SUCCESS';
export const REQUEST_GET_SERVICE_PRICE_BY_COUNTY_LIST_SUCCESS = 'REQUEST_GET_SERVICE_PRICE_BY_COUNTY_LIST_SUCCESS';

export const REQUEST_PRICING_SUCCESS = 'REQUEST_PRICING_SUCCESS';
export const REQUEST_PRICING_ERROR = 'REQUEST_PRICING_ERROR';
export const REQUEST_GET_COUNTY_PRICING_LIST_SUCCESS = 'REQUEST_GET_COUNTY_PRICING_LIST_SUCCESS';
export const REQUEST_GET_ZIP_CODE_PRICING_LIST_SUCCESS = 'REQUEST_GET_ZIP_CODE_PRICING_LIST_SUCCESS';
export const REQUEST_GET_STATE_BY_PRICING_LIST_SUCCESS = 'REQUEST_GET_STATE_BY_PRICING_LIST_SUCCESS';
export const REQUEST_GET_STATE_PRICING_LIST_SUCCESS = 'REQUEST_GET_STATE_PRICING_LIST_SUCCESS';
export const REQUEST_GET_PRICING_LIST_SUCCESS = 'REQUEST_GET_PRICING_LIST_SUCCESS';
export const REQUEST_GET_DASHBOARD_PRICING_LIST_SUCCESS = 'REQUEST_GET_DASHBOARD_PRICING_LIST_SUCCESS';
export const REQUEST_GET_STATE_LIST_SUCCESS = 'REQUEST_GET_STATE_LIST_SUCCESS';
export const REQUEST_GET_COUNTY_LIST_SUCCESS = 'REQUEST_GET_COUNTY_LIST_SUCCESS';
export const REQUEST_GET_SERVICE_LIST_SUCCESS = 'REQUEST_GET_SERVICE_LIST_SUCCESS';
export const REQUEST_GET_SERVICE_PAGE_SUCCESS = 'REQUEST_GET_SERVICE_PAGE_SUCCESS';

export const REQUEST_GET_MAIN_SERVICE_PAGE_SUCCESS = 'REQUEST_GET_MAIN_SERVICE_PAGE_SUCCESS';
export const REQUEST_GET_MAIN_SERVICE_LIST_SUCCESS = 'REQUEST_GET_MAIN_SERVICE_LIST_SUCCESS';
export const REQUEST_GET_SUB_SERVICE_LIST_SUCCESS = 'REQUEST_GET_SUB_SERVICE_LIST_SUCCESS';
export const REQUEST_GET_SUB_SERVICE_PAGE_SUCCESS = 'REQUEST_GET_SUB_SERVICE_PAGE_SUCCESS';
export const CHANGE_MAIN_SERVICE_BOOLEAN = 'CHANGE_MAIN_SERVICE_BOOLEAN';
export const CHANGE_MAIN_SERVICE_PERCENT_BOOLEAN = 'CHANGE_MAIN_SERVICE_PERCENT_BOOLEAN';

export const REQUEST_GET_ADDITIONAL_SERVICE_LIST_SUCCESS = 'REQUEST_GET_ADDITIONAL_SERVICE_LIST_SUCCESS';
export const REQUEST_GET_ADDITIONAL_SERVICE_PAGE_SUCCESS = 'REQUEST_GET_ADDITIONAL_SERVICE_PAGE_SUCCESS';
export const CHANGE_ADDITIONAL_BOOLEAN = 'CHANGE_ADDITIONAL_BOOLEAN';
export const CHANGE_ADDITIONAL_PRICE_BOOLEAN = 'CHANGE_ADDITIONAL_PRICE_BOOLEAN';

export const REQUEST_GET_DOCUMENT_TYPE_PAGE_SUCCESS = 'REQUEST_GET_DOCUMENT_TYPE_PAGE_SUCCESS';
export const REQUEST_GET_DOCUMENT_TYPE_LIST_SUCCESS = 'REQUEST_GET_DOCUMENT_TYPE_LIST_SUCCESS';

export const REQUEST_GET_DYNAMIC_LIST_SUCCESS = 'REQUEST_GET_DYNAMIC_LIST_SUCCESS';
export const REQUEST_GET_TERMS_SUCCESS = 'REQUEST_GET_TERMS_SUCCESS';
export const REQUEST_GET_CATEGORY_SUCCESS = 'REQUEST_GET_CATEGORY_SUCCESS';
export const REQUEST_GET_BLOG_BY_CATEGORY_SUCCESS = 'REQUEST_GET_BLOG_BY_CATEGORY_SUCCESS';
export const REQUEST_GET_BLOG_SUCCESS = 'REQUEST_GET_BLOG_SUCCESS';
export const REQUEST_GET_BLOG_URL_SUCCESS = 'REQUEST_GET_BLOG_URL_SUCCESS';
export const REQUEST_GET_BLOG_LIST_SUCCESS = 'REQUEST_GET_BLOG_LIST_SUCCESS';
export const REQUEST_GET_BLOG_FEATURED_LIST_SUCCESS = 'REQUEST_GET_BLOG_FEATURED_LIST_SUCCESS';

export const REQUEST_GET_ADDITIONAL_SERVICE_PRICE_LIST_SUCCESS = 'REQUEST_GET_ADDITIONAL_SERVICE_PRICE_LIST_SUCCESS';
export const REQUEST_GET_ZIP_CODE_LIST_SUCCESS = 'REQUEST_GET_ZIP_CODE_LIST_SUCCESS';
export const REQUEST_GET_COUNTRY_LIST_ERROR = 'REQUEST_GET_COUNTRY_LIST_ERROR';
export const REQUEST_ADD_COUNTRY_START = 'REQUEST_ADD_COUNTRY_START';
export const REQUEST_ADD_COUNTRY_SUCCESS = 'REQUEST_ADD_COUNTRY_SUCCESS';
export const REQUEST_ADD_COUNTRY_ERROR = 'REQUEST_ADD_COUNTRY_ERROR';
export const REQUEST_GET_TIME_DURATION_SUCCESS = 'REQUEST_GET_TIME_DURATION_SUCCESS';
export const REQUEST_GET_TIME_BOOKED_SUCCESS = 'REQUEST_GET_TIME_BOOKED_SUCCESS';
export const REQUEST_GET_DISCOUNT_PERCENT_LIST_SUCCESS = 'REQUEST_GET_DISCOUNT_PERCENT_LIST_SUCCESS';
export const REQUEST_GET_DISCOUNT_PERCENT_PAGE_SUCCESS = 'REQUEST_GET_DISCOUNT_PERCENT_PAGE_SUCCESS';
export const OPEN_MODAL = 'OPEN_MODAL';

export const REQUEST_GET_PAY_TYPE_LIST_SUCCESS = 'REQUEST_GET_PAY_TYPE_LIST_SUCCESS';

export const REQUEST_START = 'REQUEST_START';

export const CHANGE_ACTIVE = 'CHANGE_ACTIVE';
export const CHANGE_ONLINE = 'CHANGE_ONLINE';
export const CHANGE_DYNAMIC = 'CHANGE_ONLINE';
export const CHANGE_DEFAULT_INPUT = 'CHANGE_DEFAULT_INPUT';
export const CHANGE_ACTIVE_SUCCESS = 'CHANGE_ACTIVE';

export const REQUEST_ERROR = 'REQUEST_ERROR';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_ADD_ATTACHMENT_SUCCESS = 'REQUEST_ADD_ATTACHMENT_SUCCESS'
export const REQUEST_ADD_PASSPORT_SUCCESS = 'REQUEST_ADD_PASSPORT_SUCCESS'
export const REQUEST_REGISTER_AGENT_SUCCESS = 'REQUEST_REGISTER_AGENT_SUCCESS'
export const REQUEST_GET_AGENT_BY_DISCOUNT = 'REQUEST_GET_AGENT_BY_DISCOUNT'

export const REQUEST_GET_HISTORY_LIST_SUCCESS = 'REQUEST_GET_HISTORY_LIST_SUCCESS';
export const REQUEST_GET_HISTORY_TABLE_NAME_SUCCESS = 'REQUEST_GET_HISTORY_TABLE_NAME_SUCCESS';
export const REQUEST_GET_AUDIT_ONE_TABLE = 'REQUEST_GET_AUDIT_ONE_TABLE';

export const REQUEST_GET_AUDIT_TABLE_NAME_SUCCESS = 'REQUEST_GET_AUDIT_TABLE_NAME_SUCCESS';
export const REQUEST_GET_AUDIT_LIST_SUCCESS = 'REQUEST_GET_AUDIT_LIST_SUCCESS';
export const REQUEST_GET_AUDIT_ONE_LIST_SUCCESS = 'REQUEST_GET_AUDIT_ONE_LIST_SUCCESS';
export const REQUEST_GET_AUDIT_ONE_ITEM_LIST_SUCCESS = 'REQUEST_GET_AUDIT_ONE_ITEM_LIST_SUCCESS';
export const REQUEST_GET_AUDIT_ITEM_LIST_BY_AUTHOR_SUCCESS = 'REQUEST_GET_AUDIT_ITEM_LIST_BY_AUTHOR_SUCCESS';
export const REQUEST_GET_AUDIT_TOTAL_ELEMENT_COUNT = 'REQUEST_GET_AUDIT_TOTAL_ELEMENT_COUNT';
export const REQUEST_GET_USER_FOR_AUDIT = 'REQUEST_GET_USER_FOR_AUDIT';

export const REQUEST_GET_SHARING_DISCOUNT_LIST_SUCCESS = 'REQUEST_GET_SHARING_DISCOUNT_LIST_SUCCESS';
export const REQUEST_GET_SHARING_DISCOUNT_LIST_START = 'REQUEST_GET_SHARING_DISCOUNT_LIST_START';
export const REQUEST_GET_SHARING_DISCOUNT_LIST_ERROR = 'REQUEST_GET_SHARING_DISCOUNT_LIST_ERROR';

export const CHANGE_SHOW_DROPDOWN = 'CHANGE_SHOW_DROPDOWN';
export const CHANGE_SHOW_MODAL = 'CHANGE_SHOW_MODAL';
export let SET_TO_TEXT = 'SET_TO_TEXT';


export const REQUEST_GET_MAIN_SERVICES_WITH_PERCENT_START = 'REQUEST_GET_MAIN_SERVICES_WITH_PERCENT_START';
export const REQUEST_GET_MAIN_SERVICES_WITH_PERCENT_SUCCESS = 'REQUEST_GET_MAIN_SERVICES_WITH_PERCENT_SUCCESS';
export const REQUEST_GET_MAIN_SERVICES_WITH_PERCENT_ERROR = 'REQUEST_GET_MAIN_SERVICES_WITH_PERCENT_ERROR';

export const REQUEST_GET_PUBLIC_HOLIDAY_START = 'REQUEST_GET_PUBLIC_HOLIDAY_START';
export const REQUEST_GET_PUBLIC_HOLIDAY_SUCCESS = 'REQUEST_GET_PUBLIC_HOLIDAY_SUCCESS';
export const REQUEST_GET_PUBLIC_HOLIDAY_ERROR = 'REQUEST_GET_PUBLIC_HOLIDAY_ERROR';
export const REQUEST_GET_ORDER_DAY = 'REQUEST_GET_ORDER_DAY';

export const REQUEST_EDIT_MAIN_SERVICE_START = 'REQUEST_EDIT_MAIN_SERVICE_START';
export const REQUEST_EDIT_MAIN_SERVICE_SUCCESS = 'REQUEST_EDIT_MAIN_SERVICE_SUCCESS';
export const REQUEST_EDIT_MAIN_SERVICE_ERROR = 'REQUEST_EDIT_MAIN_SERVICE_ERROR';

export const REQUEST_GET_FEED_BACKS = "REQUEST_GET_FEED_BACKS";
export const REQUEST_GET_SERVICE_LIST_BY_SERVICE_SUCCESS = "REQUEST_GET_SERVICE_LIST_BY_SERVICE_SUCCESS";
export const REQUEST_GET_SERVICE_LIST_BY_SERVICE_PRICE_SUCCESS = "REQUEST_GET_SERVICE_LIST_BY_SERVICE_PRICE_SUCCESS";

export const UPDATE_STATE = "updateState";

export const REQUEST_GET_REVIEW_START = "REQUEST_GET_REVIEW_START";
export const REQUEST_GET_REVIEW_SUCCESS = "REQUEST_GET_REVIEW_SUCCESS";
export const REQUEST_GET_REVIEW_ERROR = "REQUEST_GET_REVIEW_ERROR";
export const REQUEST_DELETE_REVIEW_SUCCESS = "REQUEST_DELETE_REVIEW_SUCCESS";

export const REQUEST_SAVE_REVIEW_SUCCESS = "REQUEST_SAVE_REVIEW_SUCCESS";

export const REQUEST_GET_FAQ_START = "REQUEST_GET_FAQ_START";
export const REQUEST_GET_FAQ_SUCCESS = "REQUEST_GET_FAQ_SUCCESS";
export const REQUEST_GET_FAQ_ERROR = "REQUEST_GET_FAQ_ERROR";
export const REQUEST_DELETE_FAQ_SUCCESS = "REQUEST_DELETE_FAQ_SUCCESS";
export const REQUEST_SAVE_FAQ_SUCCESS = "REQUEST_SAVE_FAQ_SUCCESS";
export const GET_COUNTRY_PRICE_SUCCESS = "GET_COUNTRY_PRICE_SUCCESS";
export const DELETE_COUNTRY_PRICE_SUCCESS = "DELETE_COUNTRY_PRICE_SUCCESS";

export const REQUEST_POP_MODAL_API='REQUEST_POP_MODAL_API';
export const SUCCESSFUL_SAVED_EMERGENCY_INFO='SUCCESSFUL_SAVED_EMERGENCY_INFO';
export const SUCCESSFUL_EDIT_EMERGENCY_INFO='SUCCESSFUL_EDIT_EMERGENCY_INFO';
export const SUCCESSFUL_GET_EMERGENCY_INFO='SUCCESSFUL_GET_EMERGENCY_INFO';
